from typing import Any, Optional

class TestClient:
    def __init__(self, app: Any, base_url: Optional[str] = None) -> None: ...
    def get(self, path: str, **kwargs: Any) -> Any: ...
    def post(self, path: str, **kwargs: Any) -> Any: ...
    def patch(self, path: str, **kwargs: Any) -> Any: ...
    def put(self, path: str, **kwargs: Any) -> Any: ...
    def delete(self, path: str, **kwargs: Any) -> Any: ...
    def __enter__(self) -> "TestClient": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

__all__ = ["TestClient"]
