from typing import Any, Awaitable, Callable

class BaseHTTPMiddleware:
    def __init__(self, app: Any, dispatch: Callable[..., Awaitable[Any]] | None = ...) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any) -> None: ...
    async def dispatch(self, request: Any, call_next: Callable[[Any], Awaitable[Any]]) -> Any: ...

__all__ = ["BaseHTTPMiddleware"]
